export const siteConfig = {
  name: "MyPixelogs",
  url: "https://mypixelogs.com",
  description:
    "Free online PDF tools, calculators, developer utilities, editable templates, and raw design assets. No signup required.",
  ogImage: "/og-image.png",
  logo: "/icon.png",
  keywords: [
    "MyPixelogs",
    "free PDF tools",
    "PDF tools",
    "online calculators",
    "developer tools",
    "free templates",
    "business templates",
    "business documents",
    "Google Docs templates",
    "Word templates",
    "Excel templates",
    "Canva templates",
    "Canva templates",
    "PSD files",
    "design assets",
  ],
};
